import { randomUUID } from "node:crypto";
import { seedApps } from "../seed/apps.ts";
import { seedReplyTemplates, seedSignature } from "../seed/reply-templates.ts";

/**
 * Prints the seed as SQL. Nothing here connects to a database.
 *
 * Two reasons for generating a file instead of running statements:
 *
 * - the same output can be reviewed, applied to `--local`, and then applied to
 *   `--remote`, and it is obvious beforehand exactly what will run;
 * - every statement is an insert guarded by `WHERE NOT EXISTS`, so re-running
 *   the seed creates nothing twice and — the part that matters — **never
 *   overwrites a template an operator has edited in the admin screen.** The
 *   seed is where a template starts; D1 is where it lives afterwards.
 *
 *   pnpm --filter @tomokichi/admin-core seed > seed.sql
 *   pnpm --filter @tomokichi/admin-core exec wrangler d1 execute tomokichi-admin \
 *     --local --file seed.sql
 */
const now = new Date().toISOString();
const lines: string[] = [
  "-- Generated by scripts/seed.ts. Safe to run more than once.",
  "-- Every statement is a guarded insert: nothing is updated, nothing is deleted.",
  "",
];

/** SQLite string literal. The only values passed through it are the constants
 * in `seed/`, but doubling quotes is the difference between a seed file and a
 * way to run arbitrary SQL if that ever stops being true. */
const text = (value: string | undefined): string =>
  value === undefined ? "NULL" : `'${value.replace(/'/g, "''")}'`;

for (const app of seedApps) {
  const id = randomUUID();
  lines.push(
    `INSERT INTO apps (id, slug, name, platform, status, description, bundle_id, public_url, support_url, app_store_url, created_at, updated_at)`,
    `SELECT ${text(id)}, ${text(app.slug)}, ${text(app.name)}, ${text(app.platform)}, ${text(app.status)}, ${text(app.description)}, ${text(app.bundleId)}, ${text(app.publicUrl)}, ${text(app.supportUrl)}, ${text(app.appStoreUrl)}, ${text(now)}, ${text(now)}`,
    `WHERE NOT EXISTS (SELECT 1 FROM apps WHERE slug = ${text(app.slug)});`,
    "",
  );

  for (const [index, link] of (app.links ?? []).entries()) {
    lines.push(
      `INSERT INTO app_links (id, app_id, type, label, url, sort_order, created_at, updated_at)`,
      `SELECT ${text(randomUUID())}, a.id, ${text(link.type)}, ${text(link.label)}, ${text(link.url)}, ${index * 10}, ${text(now)}, ${text(now)}`,
      `  FROM apps a WHERE a.slug = ${text(app.slug)}`,
      `   AND NOT EXISTS (SELECT 1 FROM app_links l WHERE l.app_id = a.id AND l.url = ${text(link.url)});`,
      "",
    );
  }
}

for (const template of seedReplyTemplates) {
  const scope = template.appSlug
    ? `(SELECT id FROM apps WHERE slug = ${text(template.appSlug)})`
    : "NULL";
  lines.push(
    `INSERT INTO reply_templates (id, key, name, category, app_id, body, include_signature, is_active, sort_order, created_at, updated_at)`,
    `SELECT ${text(randomUUID())}, ${text(template.key)}, ${text(template.name)}, ${text(template.category)}, ${scope}, ${text(template.body)}, ${template.includeSignature ? 1 : 0}, 1, ${template.sortOrder}, ${text(now)}, ${text(now)}`,
    `WHERE NOT EXISTS (SELECT 1 FROM reply_templates WHERE key = ${text(template.key)});`,
    "",
  );
}

lines.push(
  `INSERT INTO app_mail_settings (app_id, signature_text, updated_at)`,
  `SELECT NULL, ${text(seedSignature)}, ${text(now)}`,
  `WHERE NOT EXISTS (SELECT 1 FROM app_mail_settings WHERE app_id IS NULL);`,
  "",
);

process.stdout.write(lines.join("\n"));
