import type { Locale } from "./content";
import { regionDirectories, type RegionDirectoryItem } from "./region-directories";

export type RegionFaq = { question: string; answer: string };
export type RegionSection = { heading: string; paragraphs: string[]; bullets?: string[] };
export type RegionGuide = {
  title: string;
  description: string;
  answer: string;
  facts: { label: string; value: string }[];
  directoryHeading: string;
  directoryLead: string;
  sections: RegionSection[];
  faq: RegionFaq[];
  ctaHeading: string;
  ctaBody: string;
  sourceLabel: string;
  sources: { label: string; href: string }[];
  directory: RegionDirectoryItem[];
};

type GuidePair = { ja: Omit<RegionGuide, "directory">; en: Omit<RegionGuide, "directory"> };

const source = (label: string, href: string) => ({ label, href });

const guides: Record<string, GuidePair> = {
  MY: {
    ja: {
      title: "マレーシアの州・連邦直轄領一覧｜13州と3直轄領を解説",
      description: "マレーシアの13州と3つの連邦直轄領を一覧と地図で紹介。クアラルンプールは何州？連邦直轄領とは？という疑問も解説します。",
      answer: "マレーシアには13の州と3つの連邦直轄領があります。クアラルンプール、プトラジャヤ、ラブアンは州ではなく連邦直轄領です。",
      facts: [{label:"州",value:"13"},{label:"連邦直轄領",value:"3"},{label:"Colorviaで塗れる地域",value:"16"}],
      directoryHeading: "マレーシアの13州・3連邦直轄領一覧",
      directoryLead: "州と連邦直轄領を分けて確認できます。Colorviaでは16地域を個別に記録できます。",
      sections: [
        { heading: "クアラルンプールは何州？", paragraphs: ["クアラルンプールはどの州にも属していません。マレーシアの3つの連邦直轄領のひとつです。"] },
        { heading: "連邦直轄領とは？", paragraphs: ["州とは別に連邦政府の直轄下に置かれる地域です。マレーシアではクアラルンプール、プトラジャヤ、ラブアンの3地域があります。"] },
        { heading: "半島マレーシアと東マレーシア", paragraphs: ["マレーシアは南シナ海を挟み、マレー半島側とボルネオ島側に分かれています。サバ、サラワク、ラブアンは東マレーシア側です。"] },
      ],
      faq: [
        {question:"マレーシアには州がいくつありますか？",answer:"13州です。これとは別に3つの連邦直轄領があります。"},
        {question:"クアラルンプールは州ですか？",answer:"いいえ。クアラルンプールは連邦直轄領です。"},
        {question:"マレーシアには16州あるのですか？",answer:"いいえ。正確には13州と3連邦直轄領です。"},
      ],
      ctaHeading: "訪れたマレーシアの地域を地図に残す",
      ctaBody: "Colorviaでは13州と3連邦直轄領をひとつずつ塗って、旅行の記録として残せます。",
      sourceLabel: "出典",
      sources: [source("Malaysia Government — Flag of Malaysia / states and federal territories","https://www.malaysia.gov.my/en/government/kenali-malaysia/flag-of-malaysia")],
    },
    en: {
      title: "States and Federal Territories of Malaysia: Complete List",
      description: "Explore Malaysia's 13 states and 3 federal territories. Learn whether Kuala Lumpur is a state and how Peninsular and East Malaysia differ.",
      answer: "Malaysia has 13 states and 3 federal territories. Kuala Lumpur, Putrajaya and Labuan are federal territories, not states.",
      facts: [{label:"States",value:"13"},{label:"Federal territories",value:"3"},{label:"Colorvia areas",value:"16"}],
      directoryHeading: "Malaysia's 13 states and 3 federal territories",
      directoryLead: "The list separates states from federal territories. Colorvia lets you record all 16 areas individually.",
      sections: [
        { heading: "Is Kuala Lumpur a state?", paragraphs: ["No. Kuala Lumpur is not part of any Malaysian state. It is one of Malaysia's three federal territories."] },
        { heading: "What are Malaysia's federal territories?", paragraphs: ["Malaysia has three: Kuala Lumpur, Putrajaya and Labuan. They are administered separately from the 13 states."] },
        { heading: "Peninsular Malaysia vs East Malaysia", paragraphs: ["Malaysia is split by the South China Sea. Sabah, Sarawak and Labuan lie in East Malaysia on or near Borneo, while the other states and federal territories are on the peninsula."] },
      ],
      faq: [
        {question:"How many states are in Malaysia?",answer:"Malaysia has 13 states, plus 3 federal territories."},
        {question:"Is Kuala Lumpur a state?",answer:"No. Kuala Lumpur is a federal territory."},
        {question:"Does Malaysia have 16 states?",answer:"No. It has 13 states and 3 federal territories, for 16 first-level areas in Colorvia."},
      ],
      ctaHeading: "Color the Malaysian places you've visited",
      ctaBody: "Colorvia lets you mark all 13 states and 3 federal territories one by one on your travel map.",
      sourceLabel: "Sources",
      sources: [source("Malaysia Government — states and federal territories","https://www.malaysia.gov.my/en/government/kenali-malaysia/flag-of-malaysia")],
    },
  },
  TR: {
    ja: {
      title: "トルコ81県一覧｜7地方との違い・イスタンブールを解説",
      description: "トルコ81県を一覧と地図で紹介。7地方と81県の違い、イスタンブールは都市か県か、アンカラの扱いも解説します。",
      answer: "トルコは81の県（il）で構成されています。イスタンブールやアンカラは都市名としても県名としても使われます。",
      facts: [{label:"県（il）",value:"81"},{label:"地理的地方",value:"7"},{label:"Colorviaで塗れる地域",value:"81"}],
      directoryHeading: "トルコ81県一覧",
      directoryLead: "Colorviaでは81県を個別に塗れます。7地方は行政上の県とは別の地理的な分類です。",
      sections: [
        {heading:"7地方と81県は何が違う？",paragraphs:["81県は行政区分です。一方、マルマラ、エーゲ海、地中海などの7地方は地理的な大分類で、県と同じ制度ではありません。"]},
        {heading:"イスタンブールは都市？県？",paragraphs:["どちらの意味でも使われます。イスタンブールは大都市の名前であると同時に、İstanbulという県名でもあります。"]},
        {heading:"アンカラは何県？",paragraphs:["トルコの首都アンカラも、都市名と県名が同じです。県単位の地図ではAnkaraとして1地域を構成します。"]},
      ],
      faq:[{question:"トルコには県がいくつありますか？",answer:"81県あります。"},{question:"トルコの7地方と81県は同じですか？",answer:"いいえ。81県は行政区分、7地方は地理的区分です。"},{question:"イスタンブールは県ですか？",answer:"はい。都市名であると同時に県名でもあります。"}],
      ctaHeading:"訪れたトルコの県を地図に残す",ctaBody:"Colorviaではトルコ81県を個別に塗り、訪れた地域を記録できます。",sourceLabel:"出典",sources:[source("Republic of Türkiye Ministry of Interior — Governorships","https://www.icisleri.gov.tr/valilikler")],
    },
    en:{
      title:"81 Provinces of Türkiye: Full List and Regional Guide",description:"See all 81 provinces of Türkiye and learn how they differ from the country's seven geographical regions. Istanbul and Ankara are explained too.",answer:"Türkiye has 81 provinces (il). Names such as Istanbul and Ankara refer both to major cities and to provinces.",facts:[{label:"Provinces (il)",value:"81"},{label:"Geographical regions",value:"7"},{label:"Colorvia areas",value:"81"}],directoryHeading:"All 81 provinces of Türkiye",directoryLead:"Colorvia tracks all 81 provinces individually. The seven geographical regions are broader geographic groupings rather than provinces.",sections:[{heading:"Seven regions vs 81 provinces",paragraphs:["The 81 provinces are administrative divisions. Marmara, Aegean, Mediterranean and the other geographical regions are broader geographic groupings, not the same administrative level."]},{heading:"Is Istanbul a city or a province?",paragraphs:["Both. Istanbul is the name of the famous city and also of İstanbul Province."]},{heading:"Is Ankara a city or a province?",paragraphs:["Both. Ankara is Türkiye's capital city and the name of Ankara Province."]}],faq:[{question:"How many provinces does Türkiye have?",answer:"Türkiye has 81 provinces."},{question:"Are Türkiye's seven regions the same as its provinces?",answer:"No. The seven regions are geographical groupings; the country has 81 administrative provinces."},{question:"Is Istanbul a province?",answer:"Yes. Istanbul is both a city name and a province name."}],ctaHeading:"Color the Turkish provinces you've visited",ctaBody:"Colorvia lets you mark each of Türkiye's 81 provinces individually.",sourceLabel:"Sources",sources:[source("Republic of Türkiye Ministry of Interior — Governorships","https://www.icisleri.gov.tr/valilikler")]}
  },
  ES:{
    ja:{title:"スペインの17自治州・50県一覧｜自治市との違いを解説",description:"スペイン17自治州、50県、2自治市を一覧と地図で紹介。バルセロナやマドリードは州・県・都市のどれかも解説します。",answer:"スペインには17の自治州と2つの自治市があり、その行政構造の中に50の県があります。Colorviaでは50県とセウタ・メリリャの2自治市を合わせた52地域を塗れます。",facts:[{label:"自治州",value:"17"},{label:"県",value:"50"},{label:"自治市",value:"2"},{label:"Colorviaで塗れる地域",value:"52"}],directoryHeading:"スペイン50県・2自治市一覧",directoryLead:"Colorviaは自治州より細かい県・自治市単位で旅を記録します。",sections:[{heading:"自治州と県は何が違う？",paragraphs:["自治州はより大きな自治単位で、その中に県があります。たとえばカタルーニャ自治州にはバルセロナ、ジローナ、リェイダ、タラゴナの4県があります。"]},{heading:"バルセロナは州？県？都市？",paragraphs:["バルセロナは都市名でもあり県名でもあります。バルセロナ市はカタルーニャ自治州のバルセロナ県にあります。"]},{heading:"セウタとメリリャとは？",paragraphs:["セウタとメリリャは県ではなく自治市です。Colorviaでは50県と並べて独立した2地域として記録できます。"]}],faq:[{question:"スペインには自治州がいくつありますか？",answer:"17自治州です。これとは別にセウタとメリリャの2自治市があります。"},{question:"スペインには県がいくつありますか？",answer:"50県です。"},{question:"バルセロナは何州ですか？",answer:"バルセロナ市はカタルーニャ自治州のバルセロナ県にあります。"}],ctaHeading:"訪れたスペインの県を地図に残す",ctaBody:"Colorviaでは50県と2自治市、合計52地域を個別に塗れます。",sourceLabel:"出典",sources:[source("Instituto Nacional de Estadística — territorial divisions","https://www.ine.es/en/daco/daco42/codmun/cod_ccaa_provincia_en.htm")]},
    en:{title:"Autonomous Communities and Provinces of Spain: Full Guide",description:"Understand Spain's 17 autonomous communities, 50 provinces and 2 autonomous cities, including Barcelona, Madrid, Ceuta and Melilla.",answer:"Spain has 17 autonomous communities and 2 autonomous cities, with 50 provinces in its territorial structure. Colorvia tracks the 50 provinces plus Ceuta and Melilla as 52 selectable areas.",facts:[{label:"Autonomous communities",value:"17"},{label:"Provinces",value:"50"},{label:"Autonomous cities",value:"2"},{label:"Colorvia areas",value:"52"}],directoryHeading:"Spain's 50 provinces and 2 autonomous cities",directoryLead:"Colorvia records Spain at the province/autonomous-city level, which is more detailed than autonomous communities.",sections:[{heading:"Autonomous communities vs provinces",paragraphs:["Autonomous communities are the larger self-governing units. Provinces sit within that structure. Catalonia, for example, contains Barcelona, Girona, Lleida and Tarragona provinces."]},{heading:"Is Barcelona a city, province or region?",paragraphs:["Barcelona is both a city and a province name. Barcelona city is in Barcelona Province, within the autonomous community of Catalonia."]},{heading:"What are Ceuta and Melilla?",paragraphs:["Ceuta and Melilla are autonomous cities, not provinces. Colorvia treats them as separate travel areas alongside the 50 provinces."]}],faq:[{question:"How many autonomous communities are in Spain?",answer:"Spain has 17 autonomous communities plus 2 autonomous cities."},{question:"How many provinces are in Spain?",answer:"Spain has 50 provinces."},{question:"Is Barcelona a province?",answer:"Yes. Barcelona is both a city name and the name of a province in Catalonia."}],ctaHeading:"Color the Spanish provinces you've visited",ctaBody:"Colorvia lets you mark all 50 provinces plus Ceuta and Melilla individually.",sourceLabel:"Sources",sources:[source("Instituto Nacional de Estadística — provinces and autonomous communities","https://www.ine.es/en/daco/daco42/codmun/cod_ccaa_provincia_en.htm")]}
  },
  JP:{
    ja:{title:"47都道府県一覧｜1都1道2府43県を地図で解説",description:"日本の47都道府県を一覧と地図で紹介。1都1道2府43県、地方区分、政令指定都市と東京23区の違いも解説します。",answer:"日本には47の都道府県があります。内訳は1都・1道・2府・43県で、東京都、北海道、大阪府・京都府、その他43県から成ります。",facts:[{label:"都道府県",value:"47"},{label:"内訳",value:"1都・1道・2府・43県"},{label:"Colorviaで塗れる都道府県",value:"47"}],directoryHeading:"日本の47都道府県一覧",directoryLead:"北海道から沖縄県まで、Colorviaで塗れる47都道府県を一覧で確認できます。",sections:[{heading:"1都1道2府43県とは？",paragraphs:["東京都が1都、北海道が1道、大阪府と京都府が2府、それ以外が43県です。名称は異なりますが、いずれも都道府県という地方公共団体です。"]},{heading:"東京は何県？",paragraphs:["東京都は他の県には属していません。東京都そのものが47都道府県のひとつです。"]},{heading:"地方と都道府県は同じ？",paragraphs:["関東、近畿、東北などの地方区分は複数の都道府県をまとめる地理的な分類で、都道府県と同じ行政単位ではありません。"]},{heading:"政令指定都市と東京23区",paragraphs:["政令指定都市の区は市の内部に置かれる行政区です。一方、東京23区は特別区で、法的な性格が異なります。"]}],faq:[{question:"日本には都道府県がいくつありますか？",answer:"47です。内訳は1都1道2府43県です。"},{question:"東京は何県ですか？",answer:"県には属していません。東京都が都道府県のひとつです。"},{question:"北海道は何県ですか？",answer:"北海道も県には属さず、それ自体が都道府県です。"}],ctaHeading:"訪れた都道府県を地図に残す",ctaBody:"Colorviaでは47都道府県をひとつずつ塗って、日本で訪れた場所を記録できます。",sourceLabel:"参考",sources:[source("総務省 — 地方公共団体","https://www.soumu.go.jp/main_sosiki/jichi_gyousei/bunken/index.html")]},
    en:{title:"47 Prefectures of Japan: Complete List and Map Guide",description:"See all 47 prefectures of Japan and understand Tokyo, Hokkaido, Kyoto, Osaka, regional groupings and designated cities.",answer:"Japan has 47 prefectures. The set consists of Tokyo-to, Hokkaido, Kyoto-fu, Osaka-fu and 43 prefectures ending in -ken.",facts:[{label:"Prefectures",value:"47"},{label:"Structure",value:"Tokyo + Hokkaido + Kyoto/Osaka + 43 ken"},{label:"Colorvia areas",value:"47"}],directoryHeading:"All 47 prefectures of Japan",directoryLead:"Browse every prefecture from Hokkaido to Okinawa. Colorvia lets you mark all 47 individually.",sections:[{heading:"Why do Tokyo, Hokkaido, Kyoto and Osaka have different suffixes?",paragraphs:["Japan's 47 prefectural-level governments use four suffixes: to for Tokyo, dō for Hokkaido, fu for Kyoto and Osaka, and ken for the other 43 prefectures."]},{heading:"Is Tokyo a prefecture?",paragraphs:["Tokyo is a prefectural-level government in its own right. It is not inside another prefecture."]},{heading:"Regions vs prefectures in Japan",paragraphs:["Names such as Kanto, Kansai and Tohoku group multiple prefectures geographically. They are not the same administrative level as prefectures."]}],faq:[{question:"How many prefectures are in Japan?",answer:"Japan has 47 prefectures."},{question:"Is Tokyo in a prefecture?",answer:"Tokyo is itself a prefectural-level unit; it is not inside another prefecture."},{question:"Is Hokkaido a prefecture?",answer:"Hokkaido is one of Japan's 47 prefectural-level units, using the suffix dō rather than ken."}],ctaHeading:"Color the prefectures you've visited",ctaBody:"Colorvia lets you mark all 47 Japanese prefectures one by one.",sourceLabel:"Reference",sources:[source("Ministry of Internal Affairs and Communications","https://www.soumu.go.jp/main_sosiki/jichi_gyousei/bunken/index.html")]}
  },
  FR:{
    ja:{title:"フランス101県・18地域圏一覧｜県番号と海外県を解説",description:"フランス101県と18地域圏を一覧と地図で紹介。パリ75、海外県、コルシカ2A・2B、地域圏と県の違いを解説します。",answer:"フランスには18の地域圏と101の県（département）があります。101県には本土の県だけでなく5つの海外県も含まれます。",facts:[{label:"地域圏",value:"18"},{label:"県",value:"101"},{label:"海外県",value:"5"}],directoryHeading:"フランス101県一覧",directoryLead:"県番号とあわせて101県を確認できます。Colorviaでは海外県を含めて個別に塗れます。",sections:[{heading:"地域圏と県は何が違う？",paragraphs:["地域圏（région）は県より大きな区分です。たとえばイル＝ド＝フランス地域圏にはパリ県を含む複数の県があります。"]},{heading:"パリの75とは？",paragraphs:["Parisは県名でもあり、県番号は75です。フランスの住所や識別情報では県番号を目にすることがあります。"]},{heading:"海外県も101県に含まれる？",paragraphs:["はい。グアドループ、マルティニーク、フランス領ギアナ、レユニオン、マヨットの5海外県も101県に含まれます。"]},{heading:"コルシカの2A・2B",paragraphs:["コルシカ島のCorse-du-SudとHaute-Corseは、一般的な数字2桁ではなく2Aと2Bというコードで知られます。"]}],faq:[{question:"フランスには県がいくつありますか？",answer:"101県あります。"},{question:"パリは何県ですか？",answer:"パリ県で、県番号は75です。"},{question:"フランスの海外県はいくつありますか？",answer:"5つです。"}],ctaHeading:"訪れたフランスの県を地図に残す",ctaBody:"Colorviaでは海外県を含む101県を個別に塗れます。",sourceLabel:"出典",sources:[source("INSEE — Région","https://www.insee.fr/fr/metadonnees/definition/c1696"),source("INSEE — geographical metadata","https://www.insee.fr/fr/information/2016807")]},
    en:{title:"Regions and Departments of France: All 101 Departments",description:"Browse France's 101 departments and 18 regions, including Paris 75, overseas departments and Corsica's 2A and 2B codes.",answer:"France has 18 regions and 101 departments. The 101 departments include five overseas departments as well as departments in metropolitan France.",facts:[{label:"Regions",value:"18"},{label:"Departments",value:"101"},{label:"Overseas departments",value:"5"}],directoryHeading:"All 101 departments of France",directoryLead:"Browse every department with its department number. Colorvia includes the overseas departments too.",sections:[{heading:"Regions vs departments in France",paragraphs:["A région is a larger territorial level containing departments. Île-de-France, for example, includes Paris and several surrounding departments."]},{heading:"Why is Paris 75?",paragraphs:["Paris is both the city name and a department. Its department number is 75."]},{heading:"Are overseas departments included in the 101?",paragraphs:["Yes. Guadeloupe, Martinique, French Guiana (Guyane), Réunion and Mayotte are included among France's 101 departments."]},{heading:"Why does Corsica use 2A and 2B?",paragraphs:["Corse-du-Sud and Haute-Corse are commonly identified by the special department codes 2A and 2B."]}],faq:[{question:"How many departments are in France?",answer:"France has 101 departments."},{question:"What department is Paris?",answer:"Paris is department 75."},{question:"How many overseas departments does France have?",answer:"Five are included in the 101-department total."}],ctaHeading:"Color the French departments you've visited",ctaBody:"Colorvia lets you mark all 101 departments, including the overseas departments.",sourceLabel:"Sources",sources:[source("INSEE — definition of regions","https://www.insee.fr/fr/metadonnees/definition/c1696"),source("INSEE — geographical metadata","https://www.insee.fr/fr/information/2016807")]}
  },
  KR:{
    ja:{title:"韓国の17広域自治体一覧｜ソウルは何道？広域市との違い",description:"韓国17広域自治体を一覧と地図で紹介。ソウル・仁川・釜山は何道か、広域市と道、特別自治道の違いも解説します。",answer:"韓国には17の広域自治体があります。ソウルや釜山、仁川などの大都市は周辺の道に属さず、それ自体が道と同じ最上位レベルの自治体です。",facts:[{label:"広域自治体",value:"17"},{label:"Colorviaで塗れる地域",value:"17"}],directoryHeading:"韓国17広域自治体一覧",directoryLead:"特別市、広域市、特別自治市、道、特別自治道を区分付きで一覧にしています。",sections:[{heading:"ソウルは何道？",paragraphs:["ソウルは京畿道には属していません。ソウル特別市として独立した広域自治体です。"]},{heading:"仁川は京畿道？釜山は慶尚南道？",paragraphs:["どちらも違います。仁川広域市と釜山広域市は、それぞれ周辺の道とは別の最上位自治体です。"]},{heading:"特別自治道とは？",paragraphs:["現在の韓国には江原、全北、済州の特別自治道があります。古い資料では以前の名称が残っている場合があります。"]}],faq:[{question:"韓国には広域自治体がいくつありますか？",answer:"17です。"},{question:"ソウルは京畿道ですか？",answer:"いいえ。ソウル特別市として京畿道とは別です。"},{question:"釜山は慶尚南道ですか？",answer:"いいえ。釜山広域市として別の自治体です。"}],ctaHeading:"訪れた韓国の地域を地図に残す",ctaBody:"Colorviaでは17の広域自治体を個別に塗れます。",sourceLabel:"出典",sources:[source("Korea.net — Local Governments","https://www.korea.net/Government/Constitution-and-Government/Local-Governments")]},
    en:{title:"Provinces and Metropolitan Cities of South Korea: 17 Areas",description:"See South Korea's 17 first-level local governments and understand whether Seoul, Incheon and Busan belong to surrounding provinces.",answer:"South Korea has 17 first-level local governments. Seoul, Busan, Incheon and other major metropolitan cities do not belong to surrounding provinces; they are first-level units themselves.",facts:[{label:"First-level local governments",value:"17"},{label:"Colorvia areas",value:"17"}],directoryHeading:"South Korea's 17 first-level areas",directoryLead:"The list distinguishes special cities, metropolitan cities, provinces and special self-governing units.",sections:[{heading:"Is Seoul in Gyeonggi Province?",paragraphs:["No. Seoul Special City is a separate first-level local government from Gyeonggi Province."]},{heading:"Is Incheon in Gyeonggi or Busan in South Gyeongsang?",paragraphs:["No. Incheon Metropolitan City and Busan Metropolitan City are separate first-level local governments."]},{heading:"What is a special self-governing province?",paragraphs:["Gangwon, Jeonbuk and Jeju currently use special self-governing province status. Older sources may still show earlier names."]}],faq:[{question:"How many first-level administrative areas does South Korea have?",answer:"There are 17 first-level local governments."},{question:"Is Seoul part of Gyeonggi Province?",answer:"No. Seoul is a separate first-level unit."},{question:"Is Busan in South Gyeongsang Province?",answer:"No. Busan Metropolitan City is separate from the province."}],ctaHeading:"Color the Korean regions you've visited",ctaBody:"Colorvia lets you mark all 17 first-level areas individually.",sourceLabel:"Sources",sources:[source("Korea.net — Local Governments","https://www.korea.net/Government/Constitution-and-Government/Local-Governments")]}
  },
  EG:{
    ja:{title:"エジプト27県一覧｜カイロとギザの違い・観光地の県を解説",description:"エジプト27県を一覧と地図で紹介。カイロは県か都市か、ギザのピラミッド、シャルム・エル・シェイク、ハルガダが何県かも解説します。",answer:"エジプトは27の県（governorate）に分かれています。カイロとギザは別の県で、有名なギザのピラミッドは行政区分上ギザ県にあります。",facts:[{label:"県（governorate）",value:"27"},{label:"Colorviaで塗れる地域",value:"27"}],directoryHeading:"エジプト27県一覧",directoryLead:"旅行でよく見る都市名・観光地と対応する県を確認できます。",sections:[{heading:"カイロは県？都市？",paragraphs:["Cairoは都市名として使われるだけでなく、Cairo Governorateという県名でもあります。"]},{heading:"ギザはカイロ？",paragraphs:["行政区分では別です。ギザはGiza Governorateに属し、カイロ県とは別の県です。ギザのピラミッドもギザ県側にあります。"]},{heading:"有名な旅行先は何県？",paragraphs:["シャルム・エル・シェイクは南シナイ県、ハルガダは紅海県です。旅行先の都市名とColorviaで塗る県名が異なるケースがあります。"]}],faq:[{question:"エジプトには県がいくつありますか？",answer:"27県です。"},{question:"ギザはカイロ県ですか？",answer:"いいえ。ギザ県という別の県です。"},{question:"シャルム・エル・シェイクは何県ですか？",answer:"南シナイ県です。"}],ctaHeading:"訪れたエジプトの県を地図に残す",ctaBody:"Colorviaでは27 governoratesをひとつずつ塗れます。",sourceLabel:"出典",sources:[source("Egypt State Information Service","https://sis.gov.eg/en/egypt/system-of-government/executive-authority/")]},
    en:{title:"27 Governorates of Egypt: Cairo, Giza and Travel Areas Explained",description:"Browse all 27 governorates of Egypt and learn the difference between Cairo and Giza, plus the governorates for Sharm El Sheikh and Hurghada.",answer:"Egypt is divided into 27 governorates. Cairo and Giza are separate governorates, and the Giza pyramids are administratively in Giza Governorate.",facts:[{label:"Governorates",value:"27"},{label:"Colorvia areas",value:"27"}],directoryHeading:"All 27 governorates of Egypt",directoryLead:"Use the list to connect well-known cities and travel destinations with the governorates Colorvia tracks.",sections:[{heading:"Is Cairo a city or a governorate?",paragraphs:["Both usages exist: Cairo is the famous city name and Cairo Governorate is a first-level administrative area."]},{heading:"Is Giza part of Cairo?",paragraphs:["Not administratively. Giza is in Giza Governorate, which is separate from Cairo Governorate. The Giza pyramid complex is on the Giza side."]},{heading:"What governorates are popular resorts in?",paragraphs:["Sharm El Sheikh is in South Sinai Governorate, while Hurghada is in Red Sea Governorate."]}],faq:[{question:"How many governorates are in Egypt?",answer:"Egypt has 27 governorates."},{question:"Is Giza in Cairo Governorate?",answer:"No. Giza is a separate governorate."},{question:"What governorate is Sharm El Sheikh in?",answer:"South Sinai Governorate."}],ctaHeading:"Color the Egyptian governorates you've visited",ctaBody:"Colorvia lets you mark all 27 governorates individually.",sourceLabel:"Sources",sources:[source("Egypt State Information Service","https://sis.gov.eg/en/egypt/system-of-government/executive-authority/")]}
  },
  TH:{
    ja:{title:"タイ76県＋バンコク一覧｜なぜ77県と言われる？",description:"タイの76県とバンコクを一覧と地図で紹介。タイは76県か77県か、バンコク、プーケット、パタヤ、サムイ島の地域区分を解説します。",answer:"タイの正式な県（changwat）は76あります。バンコクは県とは別の特別な地方行政区域で、地図や旅行情報では76県＋バンコクを合わせて77地域として扱うことがあります。",facts:[{label:"正式な県",value:"76"},{label:"バンコク",value:"県とは別の特別行政区域"},{label:"Colorviaで塗れる地域",value:"77"}],directoryHeading:"タイ76県＋バンコク一覧",directoryLead:"Colorviaでは76県とバンコクを合わせた77地域を個別に記録できます。",sections:[{heading:"タイは76県？77県？",paragraphs:["正式なprovinceは76です。バンコクを県と同等レベルの地域として並べる場合に、77地域・77県相当という説明が見られます。"]},{heading:"バンコクは何県？",paragraphs:["バンコクはどの県にも属していません。76県とは別の特別な地方行政区域です。"]},{heading:"プーケットは島？県？",paragraphs:["プーケットは島の名称として有名ですが、Phuket Provinceという県名でもあります。"]},{heading:"パタヤ・サムイ島は何県？",paragraphs:["パタヤはチョンブリー県、サムイ島はスラートターニー県にあります。"]}],faq:[{question:"タイには県がいくつありますか？",answer:"正式な県は76です。これとは別にバンコクがあります。"},{question:"バンコクは何県ですか？",answer:"どの県にも属していません。"},{question:"パタヤは何県ですか？",answer:"チョンブリー県です。"}],ctaHeading:"訪れたタイの地域を地図に残す",ctaBody:"Colorviaでは76県＋バンコクの77地域を個別に塗れます。",sourceLabel:"出典",sources:[source("National Statistical Office of Thailand — Statistical Yearbook","https://www.nso.go.th/public/e-book/Statistical-Yearbook/SYB-2025/14/")]},
    en:{title:"Thailand Provinces: 76 Provinces and Bangkok Explained",description:"Does Thailand have 76 or 77 provinces? Browse all 76 provinces plus Bangkok and learn where Phuket, Pattaya and Koh Samui belong.",answer:"Thailand has 76 formal provinces (changwat). Bangkok is a separate special local administrative area, so maps and travel guides often treat the country as 76 provinces plus Bangkok, or 77 province-level areas.",facts:[{label:"Formal provinces",value:"76"},{label:"Bangkok",value:"Separate special local administration"},{label:"Colorvia areas",value:"77"}],directoryHeading:"Thailand's 76 provinces plus Bangkok",directoryLead:"Colorvia tracks the 76 provinces and Bangkok as 77 separate travel areas.",sections:[{heading:"Does Thailand have 76 or 77 provinces?",paragraphs:["The formal province count is 76. Bangkok is separate, but is often listed alongside provinces as a province-level area, producing a 77-area map."]},{heading:"Is Bangkok a province?",paragraphs:["No. Bangkok does not belong to any province and has a special local administrative status."]},{heading:"Is Phuket an island or a province?",paragraphs:["Both names are used. Phuket is the famous island and also Phuket Province."]},{heading:"What provinces are Pattaya and Koh Samui in?",paragraphs:["Pattaya is in Chon Buri Province. Koh Samui is in Surat Thani Province."]}],faq:[{question:"Does Thailand have 76 or 77 provinces?",answer:"Thailand has 76 formal provinces plus Bangkok as a separate province-level area."},{question:"Is Bangkok a province?",answer:"No. Bangkok has separate special local administrative status."},{question:"What province is Pattaya in?",answer:"Chon Buri Province."}],ctaHeading:"Color the Thai places you've visited",ctaBody:"Colorvia lets you mark the 76 provinces and Bangkok as 77 separate areas.",sourceLabel:"Sources",sources:[source("National Statistical Office of Thailand — Statistical Yearbook","https://www.nso.go.th/public/e-book/Statistical-Yearbook/SYB-2025/14/")]}
  },
  BE:{
    ja:{title:"ベルギー10州・3地域一覧｜ブリュッセルは何州？",description:"ベルギーの10州と3地域を一覧と地図で紹介。ブリュッセルは何州か、フランデレン・ワロン、3共同体との違いも解説します。",answer:"ベルギーには3つの地域と10の州があります。10州はフランデレン地域とワロン地域に5州ずつあり、ブリュッセル首都圏地域はどの州にも属していません。",facts:[{label:"地域",value:"3"},{label:"州",value:"10"},{label:"共同体",value:"3"},{label:"Colorviaで塗れる地域",value:"11"}],directoryHeading:"ベルギー10州＋ブリュッセル一覧",directoryLead:"Colorviaでは10州に、州に属さないブリュッセル首都圏地域を加えた11地域を塗れます。",sections:[{heading:"ブリュッセルは何州？",paragraphs:["ブリュッセル首都圏地域はどの州にも属していません。ベルギーの3地域のひとつです。"]},{heading:"地域と州の違い",paragraphs:["ベルギーにはフランデレン、ワロン、ブリュッセル首都圏の3地域があります。州はフランデレンとワロンに5州ずつあります。"]},{heading:"3地域と3共同体は同じ？",paragraphs:["同じではありません。地域は領域に基づく制度で、共同体は主に言語・文化に関する制度です。"]},{heading:"リュクサンブール州とルクセンブルク国",paragraphs:["ベルギーにはリュクサンブール州がありますが、隣国ルクセンブルクとは別の地域です。"]}],faq:[{question:"ベルギーには州がいくつありますか？",answer:"10州です。"},{question:"ブリュッセルは何州ですか？",answer:"どの州にも属していません。ブリュッセル首都圏地域です。"},{question:"なぜColorviaでは11地域あるのですか？",answer:"10州にブリュッセル首都圏地域を加えているためです。"}],ctaHeading:"訪れたベルギーの地域を地図に残す",ctaBody:"Colorviaでは10州＋ブリュッセル首都圏地域の11地域を個別に塗れます。",sourceLabel:"出典",sources:[source("Belgium.be — Provinces","https://www.belgium.be/en/about_belgium/government/provinces"),source("Belgium.be — Regions","https://www.belgium.be/en/about_belgium/government/regions")]},
    en:{title:"Regions and Provinces of Belgium: Brussels Explained",description:"Understand Belgium's 3 regions, 10 provinces and 3 communities, including why Brussels does not belong to a province.",answer:"Belgium has 3 regions and 10 provinces. Five provinces are in the Flemish Region and five are in the Walloon Region. The Brussels-Capital Region does not belong to any province.",facts:[{label:"Regions",value:"3"},{label:"Provinces",value:"10"},{label:"Communities",value:"3"},{label:"Colorvia areas",value:"11"}],directoryHeading:"Belgium's 10 provinces plus Brussels",directoryLead:"Colorvia tracks the 10 provinces plus the Brussels-Capital Region as 11 separate travel areas.",sections:[{heading:"What province is Brussels in?",paragraphs:["None. The Brussels-Capital Region is one of Belgium's three regions and does not form part of a province."]},{heading:"Regions vs provinces in Belgium",paragraphs:["Belgium has the Flemish, Walloon and Brussels-Capital Regions. The ten provinces are divided between the Flemish and Walloon Regions."]},{heading:"Regions vs communities",paragraphs:["They are different systems. Regions are territory-based; communities primarily concern language and culture."]},{heading:"Luxembourg Province vs Luxembourg the country",paragraphs:["Belgium has a province named Luxembourg, but it is separate from the neighbouring sovereign country of Luxembourg."]}],faq:[{question:"How many provinces are in Belgium?",answer:"Belgium has 10 provinces."},{question:"What province is Brussels in?",answer:"None. Brussels-Capital is a region outside the provincial structure."},{question:"Why does Colorvia show 11 Belgian areas?",answer:"It shows the 10 provinces plus Brussels-Capital Region."}],ctaHeading:"Color the Belgian places you've visited",ctaBody:"Colorvia lets you mark the ten provinces and Brussels-Capital Region individually.",sourceLabel:"Sources",sources:[source("Belgium.be — Provinces","https://www.belgium.be/en/about_belgium/government/provinces"),source("Belgium.be — Regions","https://www.belgium.be/en/about_belgium/government/regions")]}
  },
  US:{
    ja:{title:"アメリカ50州一覧｜D.C.・プエルトリコなど56地域を解説",description:"アメリカ50州を一覧と地図で紹介。ワシントンD.C.は州か、アメリカは51州か、プエルトリコ・グアム・サイパンの扱いも解説します。",answer:"アメリカ合衆国の州は50です。ワシントンD.C.は州ではなく連邦地区で、プエルトリコ、グアム、北マリアナ諸島なども50州には含まれません。Colorviaではこれらを含む56地域を記録できます。",facts:[{label:"州",value:"50"},{label:"ワシントンD.C.",value:"州ではない"},{label:"Colorviaで塗れる地域",value:"56"}],directoryHeading:"アメリカ50州＋D.C.・地域一覧",directoryLead:"50州と、Colorviaで別々に記録できるD.C.・5地域を一覧にしています。",sections:[{heading:"アメリカは50州？51州？",paragraphs:["現在の州は50です。ワシントンD.C.やプエルトリコを州として加えて51州と数えるわけではありません。"]},{heading:"ワシントン州とワシントンD.C.の違い",paragraphs:["ワシントン州は西海岸にある50州のひとつです。ワシントンD.C.は東部にある首都の連邦地区で、州ではありません。"]},{heading:"プエルトリコやグアムは州？",paragraphs:["州ではありません。Colorviaでは旅行記録のため、プエルトリコ、グアム、米領ヴァージン諸島、北マリアナ諸島、米領サモアを50州とは別に塗れます。"]},{heading:"サイパンは何州？",paragraphs:["サイパンは州には属さず、北マリアナ諸島にあります。ColorviaではNorthern Mariana Islandsを記録します。"]}],faq:[{question:"アメリカには州がいくつありますか？",answer:"50州です。"},{question:"ワシントンD.C.は州ですか？",answer:"いいえ。連邦地区です。"},{question:"グアムはアメリカの州ですか？",answer:"いいえ。50州には含まれません。"}],ctaHeading:"訪れたアメリカの地域を地図に残す",ctaBody:"Colorviaでは50州＋D.C.＋5地域、合計56地域を個別に塗れます。",sourceLabel:"出典",sources:[source("U.S. Census Bureau — geography","https://www.census.gov/geographies/reference-files.html")]},
    en:{title:"50 U.S. States, Washington D.C. and Territories Explained",description:"Browse all 50 U.S. states and understand Washington, D.C., Puerto Rico, Guam, the Northern Mariana Islands and Colorvia's 56 travel areas.",answer:"The United States has 50 states. Washington, D.C. is a federal district rather than a state, and Puerto Rico, Guam and the other listed island areas are not part of the 50 states. Colorvia tracks 56 areas in total.",facts:[{label:"States",value:"50"},{label:"Washington, D.C.",value:"Not a state"},{label:"Colorvia areas",value:"56"}],directoryHeading:"50 U.S. states plus D.C. and five areas",directoryLead:"The directory separates the 50 states from D.C. and the five additional areas Colorvia supports.",sections:[{heading:"Does the U.S. have 50 or 51 states?",paragraphs:["The United States currently has 50 states. Washington, D.C. and Puerto Rico are not counted as a 51st state."]},{heading:"Washington State vs Washington, D.C.",paragraphs:["Washington State is a state on the Pacific coast. Washington, D.C. is the federal capital district on the East Coast and is not a state."]},{heading:"Are Puerto Rico and Guam states?",paragraphs:["No. They are not among the 50 states. Colorvia tracks Puerto Rico, Guam, the U.S. Virgin Islands, Northern Mariana Islands and American Samoa separately for travel logging."]},{heading:"Is Saipan in a U.S. state?",paragraphs:["No. Saipan is in the Northern Mariana Islands, which Colorvia records as a separate area."]}],faq:[{question:"How many states are in the U.S.?",answer:"There are 50 states."},{question:"Is Washington, D.C. a state?",answer:"No. It is a federal district."},{question:"Is Guam a U.S. state?",answer:"No. Guam is not one of the 50 states."}],ctaHeading:"Color the U.S. places you've visited",ctaBody:"Colorvia lets you mark 50 states plus D.C. and five additional areas, for 56 travel areas in total.",sourceLabel:"Sources",sources:[source("U.S. Census Bureau — geography reference files","https://www.census.gov/geographies/reference-files.html")]}
  },
  SG:{
    ja:{title:"シンガポールの地域区分｜5地域とColorviaの8旅行エリア",description:"シンガポールに州や県はある？URAの5 Planning Regionsと、Colorvia独自の8旅行エリアの違いを地図で解説します。",answer:"シンガポールには日本の都道府県やアメリカの州のような区分はありません。都市計画上はURAの5つのPlanning Regionがあり、Colorviaではそれとは別に旅行記録用の8エリアを採用しています。",facts:[{label:"URA Planning Regions",value:"5"},{label:"Colorvia旅行エリア",value:"8"},{label:"州・県",value:"なし"}],directoryHeading:"Colorviaのシンガポール8旅行エリア",directoryLead:"この8エリアはシンガポール政府の公式行政区分ではなく、旅行記録しやすいようColorviaが整理した区分です。",sections:[{heading:"シンガポールに州や県はある？",paragraphs:["日本の都道府県やアメリカの州のような第一級行政区分はありません。都市国家として別の地域制度を使っています。"]},{heading:"5つのPlanning Regionとは？",paragraphs:["URAの都市計画ではCentral、East、North、North-East、Westの5 Planning Regionsが使われます。その下にPlanning Areasがあります。"]},{heading:"Colorviaはなぜ8エリア？",paragraphs:["Colorviaの8区分は行政制度ではありません。旅先を地図上で記録しやすくすることを目的に、Central、Changi、Downtown、East、North、North-East、South、Westとして整理しています。"]},{heading:"旅行で使う地名と公式区分",paragraphs:["Marina Bay、Orchard、Chinatown、Sentosaなどの観光エリア名は、すべてが同じ種類の行政・都市計画区分ではありません。旅行地名と公式区分を混同しないことが大切です。"]}],faq:[{question:"シンガポールには州がありますか？",answer:"日本やアメリカのような州・県はありません。"},{question:"シンガポールのPlanning Regionはいくつですか？",answer:"URAでは5地域です。"},{question:"Colorviaの8地域は公式区分ですか？",answer:"いいえ。旅行記録用のColorvia独自区分です。"}],ctaHeading:"シンガポール旅行をエリアごとに残す",ctaBody:"Colorviaでは旅行記録に合わせた8エリアを塗って、訪れた場所を残せます。",sourceLabel:"出典",sources:[source("Urban Redevelopment Authority — Planning Boundaries","https://www.ura.gov.sg/Corporate/Planning/Master-Plan") ]},
    en:{title:"Regions and Areas of Singapore: 5 Planning Regions vs Colorvia's 8 Areas",description:"Does Singapore have states or provinces? Understand URA's five planning regions and Colorvia's separate eight-area travel map.",answer:"Singapore does not have state or province divisions like the U.S. or Japan. URA uses five Planning Regions for urban planning, while Colorvia separately uses eight travel-focused areas for trip logging.",facts:[{label:"URA Planning Regions",value:"5"},{label:"Colorvia travel areas",value:"8"},{label:"States / provinces",value:"None"}],directoryHeading:"Colorvia's 8 Singapore travel areas",directoryLead:"These eight areas are a Colorvia travel-logging system, not official Singapore administrative divisions.",sections:[{heading:"Does Singapore have states or provinces?",paragraphs:["No. Singapore is a city-state and does not use state or province divisions comparable to the U.S. or Japan."]},{heading:"What are Singapore's five Planning Regions?",paragraphs:["URA uses Central, East, North, North-East and West as the five Planning Regions. Planning Areas sit below that level."]},{heading:"Why does Colorvia use eight areas?",paragraphs:["Colorvia's eight areas are designed for travel logging rather than administration: Central, Changi, Downtown, East, North, North-East, South and West."]},{heading:"Tourist area names vs official planning boundaries",paragraphs:["Names such as Marina Bay, Orchard, Chinatown and Sentosa are familiar travel areas, but they are not all the same type of official administrative or planning unit."]}],faq:[{question:"Does Singapore have states?",answer:"No. Singapore does not have states or provinces in the way countries such as the U.S. or Japan do."},{question:"How many Planning Regions does Singapore have?",answer:"URA uses five Planning Regions."},{question:"Are Colorvia's eight Singapore areas official?",answer:"No. They are Colorvia's travel-focused map areas."}],ctaHeading:"Color the Singapore areas you've visited",ctaBody:"Colorvia lets you record Singapore using eight travel-focused areas designed for trip logging.",sourceLabel:"Sources",sources:[source("Urban Redevelopment Authority — Master Plan","https://www.ura.gov.sg/Corporate/Planning/Master-Plan")]}
  },
};

export function getRegionGuide(code: string, lang: Locale): RegionGuide {
  const pair = guides[code];
  if (!pair) throw new Error(`Missing region guide for ${code}`);
  return { ...pair[lang], directory: regionDirectories[code] ?? [] };
}
