import { describe, expect, it } from "vitest";

import vectors from "./moderation-vectors.json";
import {
  canonicalUUID,
  childDigest,
  normalize,
  rootFieldDigest,
  type ModerationRootField,
  type ModerationTargetKind,
} from "./moderation-digest";

/**
 * The other half of the cross-language contract.
 *
 * `RemeetTests/ModerationTargetTests.swift` reads a byte-identical copy of
 * `moderation-vectors.json`, and both are generated by
 * `scripts/moderation-vectors.py` in the Remeet repository — a third
 * implementation, so that a shared misunderstanding between the Swift and
 * TypeScript authors cannot make both suites pass.
 *
 * The reason this matters more than a usual serialisation test: if the two
 * implementations disagree, **nothing fails anywhere.** The manifest verifies,
 * parses, and matches nothing on every device, forever. There is no error to
 * notice.
 */
describe("moderation digest", () => {
  it("normalizes exactly as the app does", () => {
    for (const vector of vectors.normalization) {
      expect(normalize(vector.input), vector.name).toBe(vector.expected);
    }
  });

  it("matches the shared child-content vectors", async () => {
    for (const vector of vectors.childDigests) {
      const digest = await childDigest(vector.kind as ModerationTargetKind, vector.id);
      expect(digest, `${vector.kind}/${vector.id}`).toBe(vector.expected);
    }
  });

  it("matches the shared root-field vectors", async () => {
    for (const vector of vectors.rootFieldDigests) {
      const digest = await rootFieldDigest(
        vector.reunionID,
        vector.field as ModerationRootField,
        vector.value,
      );
      expect(digest, `${vector.field}/${vector.value}`).toBe(vector.expected);
    }
  });

  it("ignores UUID case", async () => {
    const upper = await childDigest("wish", "6F9619FF-8B86-D011-B42D-00CF4FC964FF");
    const lower = await childDigest("wish", "6f9619ff-8b86-d011-b42d-00cf4fc964ff");
    expect(upper).toBe(lower);
  });

  it("refuses anything that is not a UUID", () => {
    expect(() => canonicalUUID("not-a-uuid")).toThrow();
    // Half a UUID is the shape of a copy-paste that lost its tail, and turning
    // it into a digest would produce an action that can never match anything.
    expect(() => canonicalUUID("6f9619ff-8b86-d011")).toThrow();
  });

  it("puts the kind inside the digest", async () => {
    const id = "1b4e28ba-2fa1-11d2-883f-0016d3cca427";
    expect(await childDigest("wish", id)).not.toBe(await childDigest("statusNote", id));
  });

  it("follows the value for root fields", async () => {
    const reunion = "6f9619ff-8b86-d011-b42d-00cf4fc964ff";
    const bad = await rootFieldDigest(reunion, "sharedGroupDisplayName", "違反表現");
    const good = await rootFieldDigest(reunion, "sharedGroupDisplayName", "東京旅行");
    const again = await rootFieldDigest(reunion, "sharedGroupDisplayName", "違反表現");
    expect(bad).not.toBe(good);
    expect(bad).toBe(again);
  });

  it("folds evasion spellings together", async () => {
    const reunion = "6f9619ff-8b86-d011-b42d-00cf4fc964ff";
    const plain = await rootFieldDigest(reunion, "sharedGroupDisplayName", "BadName");
    for (const variant of ["badname", "  BadName  ", "Ｂａｄｎａｍｅ", "Bad​Name", "BAD﻿NAME"]) {
      expect(
        await rootFieldDigest(reunion, "sharedGroupDisplayName", variant),
        variant,
      ).toBe(plain);
    }
  });

  it("keeps the zero-width joiner", () => {
    expect(normalize("\u{1F468}‍\u{1F469}‍\u{1F467}")).not.toBe(
      normalize("\u{1F468}\u{1F469}\u{1F467}"),
    );
  });
});
