import { describe, expect, it } from "vitest";
import {
  canonicalUUID,
  childDigest,
  type ModerationRootField,
  type ModerationTargetKind,
  normalize,
  rootFieldDigest,
} from "./moderation-digest";
import vectors from "./moderation-vectors.json";

/**
 * The other half of the cross-language contract.
 *
 * `RemeetTests/ModerationTargetTests.swift` reads a byte-identical copy of
 * `moderation-vectors.json`, and both are generated by
 * `scripts/moderation-vectors.py` in the Remeet repository — a third
 * implementation, so that a shared misunderstanding between the Swift and
 * TypeScript authors cannot make both suites pass.
 *
 * The reason this matters more than a usual serialisation test: if the two
 * implementations disagree, **nothing fails anywhere.** The manifest verifies,
 * parses, and matches nothing on every device, forever. There is no error to
 * notice.
 */
describe("moderation digest", () => {
  it("normalizes exactly as the app does", () => {
    for (const vector of vectors.normalization) {
      expect(normalize(vector.input), vector.name).toBe(vector.expected);
    }
  });

  it("matches the shared child-content vectors", async () => {
    for (const vector of vectors.childDigests) {
      const digest = await childDigest(vector.kind as ModerationTargetKind, vector.id);
      expect(digest, `${vector.kind}/${vector.id}`).toBe(vector.expected);
    }
  });

  it("matches the shared root-field vectors", async () => {
    for (const vector of vectors.rootFieldDigests) {
      const digest = await rootFieldDigest(
        vector.reunionID,
        vector.field as ModerationRootField,
        vector.value,
      );
      expect(digest, `${vector.field}/${vector.value}`).toBe(vector.expected);
    }
  });

  it("refuses anything that is not a UUID", () => {
    expect(() => canonicalUUID("not-a-uuid")).toThrow();
    // Half a UUID is the shape of a copy-paste that lost its tail, and turning
    // it into a digest would produce an action that can never match anything.
    expect(() => canonicalUUID("6f9619ff-8b86-d011")).toThrow();
  });
});
