import { supportAppBrands } from "@tomokichi/app-site/apps";
import type { Locale } from "../data/apps";

export const supportCopy = {
  ja: {
    title: "お問い合わせ",
    metaTitle: "お問い合わせ — Tomokichi",
    description: "Tomokichiのアプリに関する不具合、ご質問、ご意見をお送りください。",
    lead: "Tomokichiのアプリに関する不具合、ご質問、ご意見をお送りください。\n内容を確認のうえ、通常3営業日以内を目安にご返信します。",
    disclosure:
      "お問い合わせへの回答や不具合調査のため、入力内容、アプリや利用環境に関する情報を送信します。返信をご希望の場合のみ、返信先メールアドレスも送信します。",
    steps: [
      {
        label: "STEP 01",
        title: "アプリと種類を選ぶ",
        body: "どのアプリの、どんな内容かが分かると調査が早くなります。",
      },
      {
        label: "STEP 02",
        title: "困っていることを書く",
        body: "再現する操作や端末・OSのバージョンがあると助かります。",
      },
      {
        label: "STEP 03",
        title: "返信を待つ",
        body: "受付IDをお伝えします。通常3営業日以内にメールでご返信します。",
      },
    ],
    app: "対象アプリ",
    category: "お問い合わせの種類",
    name: "お名前",
    required: "必須",
    optional: "任意",
    email: "返信先メールアドレス",
    replyRequested: "返信を希望する",
    replyNote: "オフのままでも送信できます。返信をご希望の場合のみ、メールアドレスをお伺いします。",
    message: "お問い合わせ内容",
    submit: "送信する",
    submitting: "送信しています…",
    privacyPrefix: "送信前に",
    privacyLink: "プライバシーポリシー",
    privacySuffix: "をご確認ください。",
    personalPrefix: "開発・制作などのご相談は",
    personalLink: "tomokichi.devのお問い合わせ窓口",
    personalSuffix: "をご利用ください。",
    emailFallbackPrefix: "フォームを利用できない場合は、",
    emailFallbackSuffix: "までメールでご連絡ください。",
    successTitle: "お問い合わせを受け付けました",
    successBody: "内容を確認のうえ、通常3営業日以内を目安にご返信します。",
    receipt: "受付ID",
    newRequest: "新しいお問い合わせを書く",
    errors: {
      form: "入力内容を確認してください。",
      emailRequired: "返信先メールアドレスを入力してください。",
      emailInvalid: "有効なメールアドレスを入力してください。",
      nameLong: "お名前は100文字以内で入力してください。",
      messageRequired: "お問い合わせ内容を入力してください。",
      messageShort: "お問い合わせ内容は10文字以上で入力してください。",
      messageLong: "お問い合わせ内容は5000文字以内で入力してください。",
      rateLimited: "短時間に送信できる回数を超えました。少し時間をおいてからお試しください。",
      deliveryFailed: "お問い合わせを送信できませんでした。時間をおいて再度お試しください。",
      serverError: "現在お問い合わせを受け付けられません。時間をおいて再度お試しください。",
      network: "インターネット接続を確認してください。",
      timeout: "送信に時間がかかっています。通信環境を確認して、もう一度お試しください。",
    },
  },
  en: {
    title: "Support",
    metaTitle: "Support — Tomokichi",
    description: "Send questions, bug reports, or feedback about Tomokichi apps.",
    lead: "Send us questions, bug reports, or feedback about Tomokichi apps.\nWe usually respond within three business days.",
    disclosure:
      "To respond and investigate issues, we send the information you enter and details about the app and your environment. We only send your reply-to email address if you ask for a reply.",
    steps: [
      {
        label: "STEP 01",
        title: "Pick the app and type",
        body: "Knowing which app and what kind of issue speeds up the search.",
      },
      {
        label: "STEP 02",
        title: "Describe what happened",
        body: "Steps that reproduce it, plus your device and OS version, help a lot.",
      },
      {
        label: "STEP 03",
        title: "Wait for a reply",
        body: "You get a reference ID, and usually an email back within three business days.",
      },
    ],
    app: "App",
    category: "Type of enquiry",
    name: "Name",
    required: "Required",
    optional: "Optional",
    email: "Reply-to email address",
    replyRequested: "I’d like a reply",
    replyNote: "You can leave this off and still send the form. We only ask for an email address if you want a reply.",
    message: "Message",
    submit: "Send",
    submitting: "Sending…",
    privacyPrefix: "Please review our",
    privacyLink: "Privacy Policy",
    privacySuffix: "before sending.",
    personalPrefix: "For development or creative work enquiries, please use",
    personalLink: "the contact form at tomokichi.dev",
    personalSuffix: ".",
    emailFallbackPrefix: "If you cannot use the form, email",
    emailFallbackSuffix: ".",
    successTitle: "We’ve received your message",
    successBody: "We’ll review it and usually reply within three business days.",
    receipt: "Reference ID",
    newRequest: "Write another message",
    errors: {
      form: "Please check the information you entered.",
      emailRequired: "Enter a reply-to email address.",
      emailInvalid: "Enter a valid email address.",
      nameLong: "Name must be 100 characters or fewer.",
      messageRequired: "Enter a message.",
      messageShort: "Message must be at least 10 characters.",
      messageLong: "Message must be 5,000 characters or fewer.",
      rateLimited: "You’ve sent too many messages in a short time. Please wait and try again.",
      deliveryFailed: "We couldn’t send your message. Please wait and try again.",
      serverError: "Support is currently unavailable. Please wait and try again.",
      network: "Check your internet connection and try again.",
      timeout: "Sending is taking too long. Check your connection and try again.",
    },
  },
} as const satisfies Record<Locale, object>;

export const supportAppOptions = [
  ...supportAppBrands.map((app) => ({
    value: app.slug,
    label: { ja: app.name, en: app.name },
  })),
  { value: "other", label: { ja: "その他", en: "Other" } },
] as const;

export const supportCategoryOptions = [
  { value: "question", label: { ja: "質問", en: "Question" } },
  { value: "bug", label: { ja: "不具合", en: "Bug report" } },
  { value: "feature", label: { ja: "機能の要望", en: "Feature request" } },
  { value: "other", label: { ja: "その他", en: "Other" } },
] as const;
